// comp1-react-webpack/src/App.js

import './App.css';
import logo from './logo.svg'

function App(props) {
  return (
    <div className="App">
      <header className="App-header-comp1">
        <img src={logo} alt="Your SVG" className='App-logo ' /><p>  Component comp1 from `{props.projectName? props.projectName: '-'}` project.</p>
      </header>
    </div>
  );
}

export default App;

// comp2-vue-webpack/src/App.vue


<script setup>
import Header from './Header.vue'
</script>

<template>
  <header>
    <!-- <img alt="Vue logo" class="logo" src="@/assets/logo.svg" width="125" height="125" /> -->

    <div class="wrapper">
      <Header msg="You did it!" />
      
      <h1>Our Application Homepage</h1>
    </div>
  </header>
</template>
